version: "3.9"
   
services:
  web:
    build: .
    command:    
      - /bin/sh
      - -c
      - |
        pytest -v;
        uvicorn main:app --host 0.0.0.0 --reload;

    volumes:
      - .:/code
    ports:
      - "8000:8000"